-- V1__add_user_table.sql is the first migration script that creates the user_entity table.
-- use of version control in the migration scripts. The version number is prefixed to the migration script name.
-- The version number is used to order the migration scripts.
-- The migration scripts are executed in the order of the version number.
-- The version number is used to identify the migration script that has already been executed.
-- The migration scripts are executed only once.
-- Any modification to the same table should be done in a new migration script with a new version number.
CREATE TABLE user_entity
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);